# Environment variables for setup.sh
ca_vm_ip="192.168.138.127"
deployment_username="ubdesk"
local_csr_path="/local/path/myfile.csr"
remote_csr_path="/remote/target-dir/myfile.csr"
local_entity_crt_path="/local/path/entity1.crt"
remote_entity_crt_path="/home/causer/certs/entity1.crt"
local_ca_crt_path="/local/path/ca.crt"
remote_ca_crt_path="/home/causer/certs/ca.crt"
ssh_key_path="$HOME/.ssh/id_rsa_entity"
ca_vm_password="password"
